### ISSUE TITLE
14 - JSON and direct to 'Slosh Balances'

### ISSUE THREAD

**Issue by ichniten** [beehive-innovation/rain-toolkit-gui#71]
<img width="933" alt="14 - JSON and direct to 'Sloshes Balances' " src="https://user-images.githubusercontent.com/54760466/205951447-40854e46-7a0b-4061-b73f-cadeb85c21c8.png">

**Comment by nagaremayur** [comment]
are you able to give me some example for using the json file as loading icon

**Comment by ichniten** [comment]
For example, after user has chosen their coins, they press ok, then their wallet comes up, (no loading screen yet) - As soon as user presses 'Confirm' in their Metamask wallet for example, the 'Add Slosh' tile has disappeared and the loading animation appears - then the 'Slosh Balances' tile appears

**Comment by nagaremayur** [comment]
fixed
