### ISSUE TITLE
15 - no scrolls

### ISSUE THREAD

**Issue by ichniten** [beehive-innovation/rain-toolkit-gui#72]
<img width="871" alt="15 - no scrolls" src="https://user-images.githubusercontent.com/54760466/205951536-939f80b5-9062-4661-b33e-b1e894945f10.png">

**Comment by nagaremayur** [comment]
On which browser you are getting this?

**Comment by ichniten** [comment]
I'm on Firefox

**Comment by nagaremayur** [comment]
Fixed
