### ISSUE TITLE
19 - link to 'Vault Balances'

### ISSUE THREAD

**Issue by ichniten** [beehive-innovation/rain-toolkit-gui#76]
<img width="818" alt="19 - link to 'vault balances'" src="https://user-images.githubusercontent.com/54760466/205952122-70b5009a-6c34-40e5-aa1b-3c737ba9b811.png">

**Comment by nagaremayur** [comment]
What do you expect @ichniten here?
If I'm not wrong you want we have to open a vault balances page when we click on vaultId

**Comment by ichniten** [comment]
<img width="619" alt="19 a" src="https://user-images.githubusercontent.com/54760466/206658019-13bbd4c8-459d-43a6-844e-8e4189ad8a8f.png">

If I click on the black underlined text here, I expect it to take me to the Slosh Balances I mean, I'll have to confirm with David M though. He'll be back this afternoon.

**Comment by ichniten** [comment]
<img width="520" alt="vault balances" src="https://user-images.githubusercontent.com/54760466/206713111-16d6a355-9bf6-4a17-b73d-149a3d67da15.png">
If I click on the black underlined text in the first image up there, I expect it to take me to the Vault Balances I mean, I've confirmed this with David M

**Comment by nagaremayur** [comment]
fixed
