### ISSUE TITLE
2 - Need to make this more robust 

### ISSUE THREAD

**Issue by ichniten** [beehive-innovation/rain-toolkit-gui#79]
<img width="665" alt="2 - Please don't close the modal until transaction is complete" src="https://user-images.githubusercontent.com/54760466/207283992-04e09522-2462-40f0-a9ee-ae36eb560b72.png">

Need to make this more robust, for example, what happens _if_ user closes the modal? How can we make this so that the modal can't be closed?

**Comment by nagaremayur** [comment]
Fixed
