### ISSUE TITLE
3 - orange button fatter

### ISSUE THREAD

**Issue by ichniten** [beehive-innovation/rain-toolkit-gui#80]
<img width="681" alt="3 - button fatter?" src="https://user-images.githubusercontent.com/54760466/207284387-7ac5b3e8-6c30-4dd6-b88d-cefffa8ba255.png">

Please make the orange button same as other buttons, for example the same one as the sloshy modal

**Comment by ichniten** [comment]
perhaps using Sentry to collect annonymous bug reports instead of this/ error prompts. I'll set up another issues to add Sentry

**Comment by nagaremayur** [comment]
Fixed
