### ISSUE TITLE
Sloshes to reload sloshes, How this works to link to comic

### ISSUE THREAD

**Issue by ichniten** [beehive-innovation/rain-toolkit-gui#82]
<img width="1265" alt="7 - if i press hTW, sloshes reloads, if i press sloshes, nothing happens, htw needs to be uploaded" src="https://user-images.githubusercontent.com/54760466/207286542-1a729c5b-76f1-4ce1-96da-fe7f32be3a32.png">

**Comment by Siddharth2207** [comment]
Resolved
